services:
  app:
    build: app
    restart: unless-stopped
    hostname: ${PROJECT_NAME}
    env_file:
      - .env
    # volumes:
    #   - ./app:/app
    networks:
      - traefik-net
      - mongo-net
      - gateway-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
  mongo-net:
    external: true
  gateway-net:
    external: true