[project]
name = "basket"
version = "0.2.0"
description = "Basket application for managing user baskets"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beanie>=2.1.0",
    "fastapi-mongo-base[sentry]>=1.8.10",
    "ipython>=9.16.1",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.2",
    "ufaas>=0.5.5",
    "usso>=0.31.6",
    "uvicorn>=0.51.0",
]

[dependency-groups]
dev = [
    # "beanie<2",
    "ipython>=9.16.1",
    "mongomock-motor>=0.0.36",
    "mypy>=2.2.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-httpx>=0.36.2",
    "pytest-timeout>=2.4.0",
    "ruff>=0.15.21",
    "ty>=0.0.58",
    "types-aiofiles>=25.1.0.20260518",
]

[tool.ruff]
line-length = 88         # Black's default line length
target-version = "py313"
fix = true
# unsafe-fixes = true
preview = true

[tool.ruff.lint]
select = [
    "F",     # Pyflakes: critical errors and unused code
    "E",     # Pyflakes: errors
    "W",     # PEP8: formatting issues
    "I",     # isort: import sorting
    "UP",    # pyupgrade: modern syntax
    "B",     # bugbear: potential bugs
    "T",     # debugger / print statement checks
    "C",     # complexity: complexity checking
    "A",     # avoids shadowing Python built-ins
    "ASYNC", # async/await syntax
    "SIM",   # simplify: cleaner code
    "PERF",  # performance optimizations
    "TRY",   # better try/excepts
    "N",     # naming conventions
    "S",     # security checks
    "ANN",   # type annotation checks
    "T20",   # no print()
    "C4",    # comprehension: better loops
    "COM",   # enforces trailing commas where needed.
    "EXE",   # executable: executable checking
    "ISC",   # implicit string concatenation
    "G",     # misuse of logging string interpolation
    "D",     # docstrings: docstring checking
    "ERA",   # remove commented code
    "RUF",   # ruff-specific improvements
]
ignore = [
    "raise-vanilla-args",
    "missing-trailing-comma",
    "function-call-in-default-argument",
    "blank-line-after-function",
    "incorrect-blank-line-before-class",
    "new-line-after-last-paragraph",
    "multi-line-summary-first-line",
    "missing-blank-line-after-last-section",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["logging-f-string", "assert"]


[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
check_untyped_defs = false
disallow_untyped_defs = false
disable_error_code = ["override"]

[tool.ty.rules]
